groups:
  - name: vertex-alerts
    rules:
      - alert: NotificationServiceHighLatency
        expr: rate(http_request_duration_seconds_sum{job="notification-service", handler="/notify"}[2m]) / rate(http_request_duration_seconds_count{job="notification-service", handler="/notify"}[2m]) > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "notification-service response time high"
          value: "Average latency exceeded 1 second (last 2 min)"
          runbook_url: "https://github.com/lerkush/observability-stack/blob/main/docs/runbook.md#notification-latency"

      - alert: CheckoutServiceErrorRateHigh
        expr: sum(rate(http_requests_total{job="checkout-service", status=~"5.."}[5m])) / sum(rate(http_requests_total{job="checkout-service"}[5m])) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "checkout-service error rate high"
          value: "5xx error rate exceeded 10% (last 5 min)"
          runbook_url: "https://github.com/lerkush/observability-stack/blob/main/docs/runbook.md#checkout-errors"